language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.3.4
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=dev  
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -U -q Django==$DJANGO_VERSION --use-mirrors"
script:
  - python quicktest.py banners
