language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.3.4
  - DJANGO_VERSION=1.4.2
install:
  - "pip install -q Django==$DJANGO_VERSION --use-mirrors"
  - "pip install -e . --use-mirrors"
script:
  - python setup.py test
